### ISSUE TITLE
Why doesn't this script work for me? 

### ISSUE THREAD

**Issue by Nickyg001** [HassanCorrigan/soundcloud-player#1]
1. Why doesn't this script work for me? He gives me these mistakes in the console.

2. is it possible to add the associated cover photo?
3. Is it possible to manage the asynchronous script without stopping the page reload?
4. Is it possible to manage mp3 data entry, titles, photos via php and wordpress?

![image](https://user-images.githubusercontent.com/33684734/124397205-e1a68780-dd0e-11eb-9743-07d2c9ddfbf8.png)

**Comment by Nickyg001** [comment]
it only works if I upload it to a server. how do i get it to work locally?

**Comment by HassanCorrigan** [comment]
@Nickyg001 You should be able to get get it running locally. E.g. Adding the audio file you want to use into the assets folder.

You can add the cover photo but the html/css would need to be updated.

Not sure what you mean with the page reload and the async script?

And yes, this could be easily added to a Wordpress implementation. You would need to assign the audio source dynamically based on the uploaded audio files. I'm not too familiar with Wordpress however.

**Comment by Nickyg001** [comment]
No locally just does not work for me from that error fetch .. (even if the sample.mp3 is present).

I am also a dj as a hobby, I wanted to create a wordpress site to put dj sets ..
I wanted to create a player like yours or very similar to be fixed at the bottom.

Create an Html in the body that shows me the cover, the title and a play button (a button in practice), clicking the button me other in the player the mp3 and transfers both the textual data (author title) and the cover image.
With wordpress if the data are managed in the html (url, title etc.) I can manage them from wordpress dynamically in the backend then that data should be sent to the wavesurfer.js player script

Now the mp3 url links are inside the javascript file.

I tried to make wavesurfer work, I download the examples but it doesn't work it gives me errors, and the guide I can't always understand how to implement the functions.

**Comment by HassanCorrigan** [comment]
@Nickyg001 I understand. I can’t help out with the Wordpress/PHP side of things unfortunately. 

However, I have built a similar re-usable site you might be interested in. 

https://github.com/HassanCorrigan/dj-profile

You can check out the live version here: https://dj-profile.vercel.app/

It is very easy to add your own mixes, songs, album covers etc. All you need to do is upload the files to Dropbox and add the links into the data.json file. It can be hosted for free on Vercel too. Hope that can help in some way. It sounds like what you are looking to create.

**Comment by Nickyg001** [comment]
yes I had also seen this app ...

Let's say the soundcloud script could be fine too (with some changes). For now my problem is to make it work locally in order to understand how it works and how to modify it for my purpose.
But apparently I never had much luck with wavesurfer!

**Comment by HassanCorrigan** [comment]
You'll need to run it with something such as LiveServer to test it locally. Are you using VS Code text editor? If you are, install the Extension 'Live Server'. Here is a tutorial which will give you some info if you aren't familiar.

https://www.freecodecamp.org/news/vscode-live-server-auto-refresh-browser/

Opening the index.html file locally won't work unless you run it with something like LiveServer unfortunately.

**Comment by Nickyg001** [comment]
yes actually before I was able to make it work in live server :)
